# See https://kind.sigs.k8s.io/docs/user/configuration/
# kind create cluster --config kind-api-cluster.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# TODO Change here if you need to expose ports_
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31022
    hostPort: 31022
    listenAddress: "127.0.0.1"
    protocol: TCP
  - containerPort: 31090
    hostPort: 31090
    listenAddress: "127.0.0.1"
    protocol: TCP
- role: worker
