site_name: Kubernetes java debugging

nav:
  - Agenda: index.md
  - 1. Kubernetes setup: 01-kind-setup.md
  - 2. A java application: 02-java-application.md
  - 3. Soak test with k6s: 03-k6s.md
  - 4. All set up: 04-all-set-up.md
  - Debugging:
      - 5. Remote debug: 05-remote-debug.md
      - 6. JKube: 06-jkube.md
      - 7. Kubernetes debugging: 07-kubernetes-debug.md
      - 8. JCMD / JFR / JMC: 08-jcmd-jfr-jmc.md
  - Key points: key-points.md
theme: readthedocs