site_name: Kubernetes java debugging

nav:
  - Agenda:
      - 0. Plan: index.md
      - 1. Our setup: 01-all-set-up.md
      - 2. Kubernetes setup: 02-kind-setup.md
      - 3. A java application: 03-java-application.md
      - 4. Soak test with k6s: 04-k6s.md
  - Debugging:
      - 5. Remote debug: 05-remote-debug.md
      - 6. JKube: 06-jkube.md
      - 7. Kubernetes debugging: 07-kubernetes-debug.md
      - 8. JCMD / JFR / JMC: 08-jcmd-jfr-jmc.md
  - Key points: key-points.md
theme: readthedocs