site_name: Kubernetes java debugging

nav:
  - Agenda: agenda.md
  - Kubernetes setup: kind-setup.md
  - Java application: java-application.md
  - Debugging:
      - Remote debug: remote-debug.md
      - JKube: jkube.md
  - About mkdocs:
      - About: index.md

theme: readthedocs