site_name: Kubernetes java debugging

nav:
  - Agenda: index.md
  - Kubernetes setup: kind-setup.md
  - A java application: java-application.md
  - Soak test with k6s: k6s.md
  - All set up: all-set-up.md
  - Debugging:
      - Remote debug: remote-debug.md
      - JKube: jkube.md
      - Kubernetes debugging: kubernetes-debug.md

theme: readthedocs