apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sdebug
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: k8sdebug
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8sdebug
    spec:
      # shareProcessNamespace: true
      serviceAccountName: k8sdebug-sa
      containers:
        - name: k8sdebug
          image: k8sdebug:0.0.1-SNAPSHOT
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "to-be-overridden"
          ports:
            - containerPort: 8080
              name: http
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 4
            failureThreshold: 40
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 500m
              memory: 600Mi
            limits:
              memory: 600Mi
          imagePullPolicy: IfNotPresent
