apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sdebug
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: k8sdebug
  template:
    spec:
      # This will make attached debug process share the PID address space: NOT FOR production
      shareProcessNamespace: true
      containers:
        - name: k8sdebug ##5
          #image: k8sdebug:manual # {"$imagepolicy": "apps:k8sdebug"}
          image: k8sdebug:0.0.1-SNAPSHOT # JIB crashes too quickly
          env:
            - {}
            - name: MEMORY_SETTINGS
              value: "-XX:+UseZGC -Xss256K -Xmx64M -XX:ReservedCodeCacheSize=64M -XX:MaxMetaspaceSize=64M -XX:MaxDirectMemorySize=5M"
            - name: REMOTE_DEBUG ##6
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
            - name: JAVA_TOOL_OPTIONS
              value: "$(REMOTE_DEBUG)"
              #value: "$(MEMORY_SETTINGS) $(REMOTE_DEBUG)"
            - name: APP_ACCELERATOR # Increase value use more memory
              value: "1"
            # Setting buildpack value, helps running the application with Jib
            # See: https://paketo.io/docs/howto/java/#configure-the-jvm-at-runtime
            #- name: BPL_JVM_THREAD_COUNT
            #  value: "70"
# 600M is what is currently set in the base, keeping outcommented setting for easy adjustment
#          resources:
#            requests:
#              cpu: 500m
#              memory: 600Mi
#            limits:
#              memory: 600Mi
      terminationGracePeriodSeconds: 2
