apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: jk8sdebug
  name: jk8sdebug
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: jk8sdebug
