apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnpg-cluster
resources:
- pg-cluster.yaml
- prometheusrule.yaml
- pg-cluster-ns.yaml
# - acpicurio-db.yaml
- apicurio-secret.yaml
