apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
spec:
  instances: 1
  storage:
    size: 1Gi
  postgresql:
    parameters:
      max_connections: "10"
      shared_buffers: 16MB
  resources:
    requests:
      cpu: "50m"
      memory: "300Mi"
    limits:
      memory: "300Mi"
  bootstrap:
    initdb:
      encoding: "UTF8"
      database: "apicuriodb"
      owner: apicurio
  managed:
    roles:
      - name: apicurio
        comment: "Apicurio database"
        createdb: false
        createrole: false
        ensure: present
        login: true
        passwordSecret:
          name: apicurio
        superuser: false
  monitoring:
    enablePodMonitor: true
