{
 "title": "Apache Camel Data metrics",
 "description": "Metrics that are produced by Apache Camel 1) out of the box per each route 2) manually added to meter the critical parts of the Camel routes",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "sum by(routeId)(rate(CamelMessageHistory_seconds_sum{}[5m]))",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by(routeId)(rate(CamelMessageHistory_seconds_sum{}[5m]))"
    }
   ]
  },
  {
   "title": "Routes details metrics mean (sum/count)",
   "type": "graph",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(\r\n  {__name__=~\"camel.*sum\"},\"name_label\",\"$1\",\"__name__\", \"(.+)sum\"\r\n) /\r\nlabel_replace(\r\n  {__name__=~\"camel.*count\"},\"name_label\",\"$1\",\"__name__\", \"(.+)count\"\r\n)"
    }
   ]
  },
  {
   "title": "Routes details metrics max",
   "type": "graph",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"camel.*max\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")"
    }
   ]
  },
  {
   "title": "rate(label_replace({__name__=~\"camel_proxy.*count\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[5m:])",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"camel.*count\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[5m:])"
    }
   ]
  },
  {
   "title": "Routes details metrics mean",
   "type": "graph",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(label_replace({__name__=~\"camel.*sum\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")[5m:])"
    }
   ]
  },
  {
   "title": "Routes details metrics count",
   "type": "graph",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace({__name__=~\"camel.*count\"},\"name_label\",\"$1\",\"__name__\", \"(.+)\")"
    }
   ]
  }
 ]
}