{
 "title": "HikariCP (Prometheus)",
 "description": "Data about HIkariCP connection pools exposed by HikariCP Prometheus exporter",
 "tags": [
  "prometheus",
  "hikaricp",
  "jdbc"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(hikaricp_connections, pod)"
    }
   },
   {
    "name": "hikaricp_pool_name",
    "query": {
     "query": "label_values(hikaricp_connections{pod=~\"$pod\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_active{pod=~\"$pod\", pool=\"$hikaricp_pool_name\"})",
     "legendFormat": "Active connections"
    },
    {
     "expr": "sum(hikaricp_connections_idle{pod=~\"$pod\", pool=\"$hikaricp_pool_name\"})",
     "legendFormat": "Idle connections"
    },
    {
     "expr": "sum(hikaricp_pending_threads{pod=~\"$pod\", pool=\"$hikaricp_pool_name\"})",
     "legendFormat": "Pending threads"
    }
   ]
  },
  {
   "title": "Min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_min{pod=~\"$pod\", pool=\"$hikaricp_pool_name\"})"
    }
   ]
  },
  {
   "title": "Connections per pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hikaricp_connections_active{pod=~\"$pod\", pool=\"$hikaricp_pool_name\"}",
     "legendFormat": "Active connections {{ pod }}"
    },
    {
     "expr": "hikaricp_pending_threads{pod=~\"$pod\", pool=\"$hikaricp_pool_name\"}",
     "legendFormat": "Pending threads {{ pod }}"
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_max{pod=~\"$pod\", pool=\"$hikaricp_pool_name\"})"
    }
   ]
  },
  {
   "title": "Total Timeout",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_timeout_total{pod=~\"$pod\", pool=\"$hikaricp_pool_name\"})"
    }
   ]
  },
  { "title": "Connection durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Connections Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(hikaricp_connections_usage_seconds_sum{pod=~\"$pod\", pool=\"$hikaricp_pool_name\"}[$__rate_interval]) / irate(hikaricp_connections_usage_seconds_count{pod=~\"$pod\", pool=\"$hikaricp_pool_name\"}[$__rate_interval])",
     "legendFormat": "Usage time {{ pod }}"
    },
    {
     "expr": "irate(hikaricp_connections_creation_seconds_sum{pod=~\"$pod\", pool=\"$hikaricp_pool_name\"}[$__rate_interval]) / irate(hikaricp_connections_creation_seconds_count{pod=~\"$pod\", pool=\"$hikaricp_pool_name\"}[$__rate_interval])",
     "legendFormat": "Creation time {{ pod }}"
    },
    {
     "expr": "irate(hikaricp_connections_acquired_seconds_sum{pod=~\"$pod\", pool=\"$hikaricp_pool_name\"}[$__rate_interval]) / irate(hikaricp_connections_acquired_seconds_count{pod=~\"$pod\", pool=\"$hikaricp_pool_name\"}[$__rate_interval])",
     "legendFormat": "Connection acquired {{ pod }}"
    }
   ]
  },
  {
   "title": "Connection usage",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(round(rate(hikaricp_connections_usage_seconds_max{pod=~\"$pod\",pool=\"$hikaricp_pool_name\"}[$__interval]) * $__interval_ms )) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Connection creation",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "sum(round(rate(hikaricp_connections_usage_seconds_max{pod=~\"$pod\",pool=\"$hikaricp_pool_name\"}[$__interval]) * $__interval_ms )) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Connection acquired time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "sum(round(rate(hikaricp_connections_acquired_nanos_bucket{pod=~\"$pod\",pool=\"$hikaricp_pool_name\"}[$__interval]) * $__interval_ms )) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}