apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - run-k6-test.yaml
configMapGenerator:
  - name: scenario
    options:
      disableNameSuffixHash: true
      immutable: true
    files:
      - index-test.js
      - run-soak-test.js