apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: run-k6-test
spec:
  parallelism: 1
  script:
    configMap:
      name: scenario
      file: run-soak-test.js
  separate: false
  # Removes all resources upon completion
  #cleanup: post
  arguments: -o experimental-prometheus-rw --env K6_PROMETHEUS_RW_SERVER_URL=http://prometheus-k8s.monitoring:9090/api/v1/write
#  runner:
#    image: <custom-image>
#    metadata:
#      labels:
#        cool-label: foo
#      annotations:
#        cool-annotation: bar
#    securityContext:
#      runAsUser: 1000
#      runAsGroup: 1000
#      runAsNonRoot: true
#    resources:
#      limits:
#        cpu: 200m
#        memory: 1000Mi
#      requests:
#        cpu: 100m
#        memory: 500Mi
#  starter:
#    image: <custom-image>
#    metadata:
#      labels:
#        cool-label: foo
#      annotations:
#        cool-annotation: bar
#    securityContext:
#      runAsUser: 2000
#      runAsGroup: 2000
#      runAsNonRoot: true
