apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: k8sdebug
  name: k8sdebug
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: http
      scheme: http
      path: /actuator/prometheus
  selector:
    matchLabels:
      app.kubernetes.io/name: k8sdebug