apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: k8sdebug
  name: k8sdebug
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: http
      scheme: http
      path: /actuator/prometheus
      relabelings:
        - sourceLabels: [ __meta_kubernetes_pod_node_name ]
          action: replace
          targetLabel: instance
        - sourceLabels: [ job ]
          targetLabel: application
          action: replace
      metricRelabelings:
        - action: labeldrop
          regex: (app_metric_with_error)
  selector:
    matchLabels:
      app.kubernetes.io/name: k8sdebug
  namespaceSelector:
    matchNames:
      - apps
