apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- grafana-config.yaml
- grafana-dashboardDatasources.yaml
- grafana-dashboardSources.yaml
- grafana-deployment.yaml
- grafana-networkPolicy.yaml
- grafana-prometheusRule.yaml
- grafana-service.yaml
- grafana-serviceAccount.yaml
- grafana-serviceMonitor.yaml
patches:
  - target:
      kind: Deployment
      name: grafana
    path: grafana-environment.yaml
configMapGenerator:
  - name: grafana-dashboard-jvm
    files:
      - grafana-dashboard-definitions/jvm/jvm-micrometer_rev1_num2.json # https://grafana.com/grafana/dashboards/11955-jvm-micrometer/
      - grafana-dashboard-definitions/jvm/jvm-actuator_rev1.json
      - grafana-dashboard-definitions/jvm/jvm-micrometer-in-k8s_rev1.json # https://grafana.com/grafana/dashboards/13788-jvm-micrometer-in-k8s/
      - grafana-dashboard-definitions/jvm/spring-boot-statistics_rev3.json
      #- grafana-dashboard-definitions/jvm/hikaricp-connection-pools_rev1-17313.json # https://grafana.com/grafana/dashboards/17313-hikaricp-connection-pools/
      #- grafana-dashboard-definitions/jvm/camel-16354.json # https://grafana.com/grafana/dashboards/16354-data-integration-check/
      - grafana-dashboard-definitions/jvm/17360_rev1.json # https://grafana.com/grafana/dashboards/17360-spring-http-example/
  - name: grafana-dashboard-alertmanager-overview
    files:
      - grafana-dashboard-definitions/alertmanager-overview/alertmanager-overview.json
  - name: grafana-dashboard-node-exporter
    files:
      - grafana-dashboard-definitions/node-exporter/nodes.json
      - grafana-dashboard-definitions/node-exporter/node-cluster-rsrc-use.json
      - grafana-dashboard-definitions/node-exporter/node-rsrc-use.json
  - name: grafana-dashboard-prometheus
    files:
      # N/A - grafana-dashboard-definitions/prometheus/prometheus-remote-write.json
      - grafana-dashboard-definitions/prometheus/prometheus.json
  - name: grafana-dashboard-grafana
    files:
      - grafana-dashboard-definitions/grafana-overview/grafana-overview.json
  - name: grafana-dashboard-nginx-controller
    files:
      - grafana-dashboard-definitions/nginx-controller/nginx-controller-overview.json
  - name: grafana-dashboard-flux
    files:
      - grafana-dashboard-definitions/flux/flux2_rev1.json
      # flux2_rev1 is better than cluster.json
      # - grafana-dashboard-definitions/flux/cluster.json
      - grafana-dashboard-definitions/flux/control-plane.json
  - name: grafana-dashboard-kubernetes
    files:
      - grafana-dashboard-definitions/kubernetes/cluster-total.json
      - grafana-dashboard-definitions/kubernetes/k8s-resources-namespace.json
      - grafana-dashboard-definitions/kubernetes/k8s-resources-workload.json
      - grafana-dashboard-definitions/kubernetes/namespace-by-pod.json
      - grafana-dashboard-definitions/kubernetes/pod-total.json
      - grafana-dashboard-definitions/kubernetes/controller-manager.json
      - grafana-dashboard-definitions/kubernetes/k8s-resources-node.json
      - grafana-dashboard-definitions/kubernetes/k8s-resources-workloads-namespace.json
      - grafana-dashboard-definitions/kubernetes/namespace-by-workload.json
      - grafana-dashboard-definitions/kubernetes/scheduler.json
      - grafana-dashboard-definitions/kubernetes/k8s-resources-cluster.json
      - grafana-dashboard-definitions/kubernetes/k8s-resources-pod.json
      - grafana-dashboard-definitions/kubernetes/kubelet.json
      - grafana-dashboard-definitions/kubernetes/persistentvolumesusage.json
      - grafana-dashboard-definitions/kubernetes/workload-total.json
