spring.application.name: k8sdebug
management.tracing.sampling.probability: 1.0
management.endpoints.web.exposure.include: health,info,prometheus

# For Exemplars to work we need histogram buckets
management.metrics.distribution.percentiles-histogram.http.server.requests: true
