name: Build

on:
  push:
    paths:
      - 'spring-app/**'

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./spring-app
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 1.23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Build with Maven
      run: ./mvnw  -B package --file pom.xml
      env:
        GITHUB_ACTIONS: 'true'
